--Migration script

INSERT INTO ADDRESS (STREETNUMBER, STREETNAME, COUNTRY, PROVINCE, CITY)
SELECT DISTINCT STREETNUMBER, STREETNAME, COUNTRY, PROVINCE, CITY
FROM ADDRESSOLD
WHERE STREETNUMBER IS NOT NULL;

INSERT INTO STORE (STORENAME,STORETYPE)
SELECT DISTINCT 
			CASE WHEN INSTR(S.STORENAME, '(') > 0 THEN 
				TRIM(SUBSTR(S.STORENAME,1,INSTR(S.STORENAME, '(')-1))
			ELSE S.STORENAME
			END STORENAME,
			S.STORETYPE
FROM STOREOLD S;

INSERT INTO STORECHAIN(STOREID, ADDRESSID, CHAINDESCRIPTION, PHONE, EMAIL)
SELECT SN.STOREID, AN.ADDRESSID, O.STORECHAINDESC, O.PHONE, O.EMAIL
FROM (
	SELECT CASE WHEN INSTR(S.STORENAME, '(') > 0 THEN 
					TRIM(SUBSTR(S.STORENAME,1,INSTR(S.STORENAME, '(')-1))
				ELSE S.STORENAME
				END STORENAME,
				CASE WHEN INSTR(S.STORENAME, '(') > 0 THEN 
					REPLACE(TRIM(SUBSTR(S.STORENAME,INSTR(S.STORENAME, '(') + 1)),')','')
				END STORECHAINDESC,
				A.STREETNUMBER,
				A.STREETNAME,
				A.COUNTRY,
				A.PROVINCE, 
				A.CITY,
				CASE WHEN A.PHONE = '' THEN NULL ELSE A.PHONE END PHONE,
				CASE WHEN A.EMAIL = '' THEN NULL ELSE A.EMAIL END EMAIL
	FROM STOREOLD S
	JOIN ADDRESSOLD A ON A.ADDRESSID = S.ADDRESSID) O
JOIN STORE SN ON O.STORENAME = SN.STORENAME 
LEFT JOIN ADDRESS AN ON (AN.STREETNUMBER = O.STREETNUMBER 
			AND AN.STREETNAME = O.STREETNAME 
			AND AN.COUNTRY = O.COUNTRY
			AND AN.PROVINCE = O.PROVINCE
			AND AN.CITY = O.CITY)
;

INSERT INTO RECEIPT (RECEIPTID, STORECHAINID, RECEIPTDATE, PAYMENTTYPE, BASEAMOUNT, TAXAMOUNT,TAXPERCENTAGE, TIPAMOUNT, TOTALAMOUNT, ROUNDAMOUNT, REVERSAL, PAYEE)
SELECT  R.RECEIPTID,
		SN.STORECHAINID,
		R.RECEIPTDATE,
		R.PAYMENTTYPE,
		R.BASEAMOUNT,
		R.TAXAMOUNT,
		CASE WHEN R.TAXAMOUNT != 0 THEN (R.TAXAMOUNT / R.BASEAMOUNT)*100
			ELSE 0
		END,
		R.TIPAMOUNT,
		R.TOTALAMOUNT,
		R.ROUNDAMOUNT,
		R.REVERSAL,
		R.PAYEE
FROM RECEIPTOLD R
JOIN (SELECT S.STOREID, 
						S.ADDRESSID, 
						CASE WHEN INSTR(S.STORENAME, '(') > 0 THEN TRIM(SUBSTR(S.STORENAME,1,INSTR(S.STORENAME, '(')-1))
						ELSE S.STORENAME END STORENAME
			FROM STOREOLD S ) S ON R.STOREID = S.STOREID
JOIN ADDRESSOLD A ON S.ADDRESSID = A.ADDRESSID
JOIN (SELECT SN.STORENAME, SC.STORECHAINID, AN.STREETNUMBER, AN.STREETNAME, AN.COUNTRY, AN.PROVINCE, AN.CITY
		FROM STORE SN
		JOIN STORECHAIN SC ON SC.STOREID = SN.STOREID
		LEFT JOIN ADDRESS AN ON SC.ADDRESSID = AN.ADDRESSID) SN ON SN.STORENAME = S.STORENAME
																	AND (
																			(SN.STREETNAME IS NULL AND A.STREETNAME = '') 
																			OR (														
																					A.STREETNUMBER = SN.STREETNUMBER
																					AND A.STREETNAME = SN.STREETNAME
																					AND A.COUNTRY = SN.COUNTRY
																					AND A.CITY = SN.CITY
																					AND A.PROVINCE = SN.PROVINCE))
;









