--Migration script

INSERT INTO ADDRESSNEW (STREETNUMBER, STREETNAME, COUNTRY, PROVINCE, CITY)
SELECT DISTINCT STREETNUMBER, STREETNAME, COUNTRY, PROVINCE, CITY
FROM ADDRESS
WHERE STREETNUMBER IS NOT NULL;

INSERT INTO STORENEW (STORENAME,STORETYPE)
SELECT DISTINCT 
			CASE WHEN INSTR(S.STORENAME, '(') > 0 THEN 
				TRIM(SUBSTR(S.STORENAME,1,INSTR(S.STORENAME, '(')-1))
			ELSE S.STORENAME
			END STORENAME,
			S.STORETYPE
FROM STORE S;

INSERT INTO STORECHAIN(STOREID, ADDRESSID, CHAINDESCRIPTION, PHONE, EMAIL)
SELECT SN.STOREID, AN.ADDRESSID, O.STORECHAINDESC, O.PHONE, O.EMAIL
FROM (
	SELECT CASE WHEN INSTR(S.STORENAME, '(') > 0 THEN 
					TRIM(SUBSTR(S.STORENAME,1,INSTR(S.STORENAME, '(')-1))
				ELSE S.STORENAME
				END STORENAME,
				CASE WHEN INSTR(S.STORENAME, '(') > 0 THEN 
					REPLACE(TRIM(SUBSTR(S.STORENAME,INSTR(S.STORENAME, '(') + 1)),')','')
				END STORECHAINDESC,
				A.STREETNUMBER,
				A.STREETNAME,
				A.COUNTRY,
				A.PROVINCE, 
				A.CITY,
				CASE WHEN A.PHONE = '' THEN NULL ELSE A.PHONE END PHONE,
				CASE WHEN A.EMAIL = '' THEN NULL ELSE A.EMAIL END EMAIL
	FROM STORE S
	JOIN ADDRESS A ON A.ADDRESSID = S.ADDRESSID) O
JOIN STORENEW SN ON O.STORENAME = SN.STORENAME 
LEFT JOIN ADDRESSNEW AN ON (AN.STREETNUMBER = O.STREETNUMBER 
			AND AN.STREETNAME = O.STREETNAME 
			AND AN.COUNTRY = O.COUNTRY
			AND AN.PROVINCE = O.PROVINCE
			AND AN.CITY = O.CITY)
;

INSERT INTO RECEIPTNEW (RECEIPTID, STOREID, RECEIPTDATE, PAYMENTTYPE, BASEAMOUNT, TAXAMOUNT,TAXPERCENTAGE, TIPAMOUNT, TOTALAMOUNT, ROUNDAMOUNT, REVERSAL, PAYEE)
SELECT  RECEIPTID,
		STOREID,
		RECEIPTDATE,
		PAYMENTTYPE,
		BASEAMOUNT,
		TAXAMOUNT,
		CASE WHEN TAXAMOUNT != 0 THEN ()TAXAMOUNT / BASEAMOUNT)*100
			ELSE 0
		END,
		TIPAMOUNT,
		TOTALAMOUNT,
		ROUNDAMOUNT,
		REVERSAL,
		PAYEE
FROM RECEIPTOLD;










