ALTER TABLE ADDRESS RENAME TO ADDRESSOLD;
ALTER TABLE STORE RENAME TO STOREOLD;
ALTER TABLE RECEIPT RENAME TO RECEIPTOLD;
ALTER TABLE PAYMENTITEM RENAME TO PAYMENTITEMOLD;
ALTER TABLE PAYMENT RENAME TO PAYMENTOLD;

CREATE TABLE ADDRESS
(
	ADDRESSID		INTEGER	PRIMARY KEY,
	STREETNUMBER 	INTEGER,
	STREETNAME		TEXT,
	COUNTRY			TEXT,
	PROVINCE		TEXT,
	CITY			TEXT
);

CREATE TABLE STORECHAIN
(
	STORECHAINID 		INTEGER PRIMARY KEY,
	STOREID				INTEGER,
	ADDRESSID			INTEGER,
	CHAINDESCRIPTION	TEXT,
	PHONE				TEXT,
	EMAIL				TEXT,
	FOREIGN KEY(STOREID) REFERENCES STORE(STOREID),
	FOREIGN KEY(ADDRESSID) REFERENCES ADDRESS(ADDRESSID)
);

CREATE TABLE STORE
(
	STOREID			INTEGER PRIMARY KEY,
	STORENAME		TEXT,
	STORETYPE		INTEGER,
	DESCRIPTION		TEXT
);

CREATE TABLE RECEIPT
(
	RECEIPTID		INTEGER PRIMARY KEY,
	STORECHAINID	INTEGER,
	RECEIPTDATE		TEXT,
	PAYMENTTYPE		INTEGER,
	BASEAMOUNT		REAL,
	TAXAMOUNT		REAL,
	TAXPERCENTAGE	REAL,
	TIPAMOUNT		REAL,
	TOTALAMOUNT		REAL,
	ROUNDAMOUNT		REAL,
	REVERSAL		INTEGER,
	PAYEE			INTEGER,
	FOREIGN KEY (STORECHAINID) REFERENCES STORECHAIN(STORECHAINID)
);

CREATE TABLE PAYMENT
(
	PAYMENTID 		INTEGER PRIMARY KEY,
	LASTPAYMENTDATE	TEXT,
	NEXTPAYMENTDATE TEXT,
	PAYMENTNAME		TEXT,
	DESCRIPTION		TEXT,
	PAYMENTPERIOD	INTEGER
);

CREATE TABLE PAYMENTITEM
(
	PAYMENTITEMID	INTEGER PRIMARY KEY,
	PAYMENTDATE		TEXT,
	PAYMENTID		INTEGER,
	RECEIPTID		INTEGER,	
	FOREIGN KEY(RECEIPTID) REFERENCES RECEIPT(RECEIPTID),
	FOREIGN KEY(PAYMENTID) REFERENCES PAYMENT(PAYMENTID)
);