DROP TABLE ADDRESSOLD;
DROP TABLE LOG;
DROP TABLE PAYMENTOLD;
DROP TABLE PAYMENTITEMOLD;
DROP TABLE ENUM;
DROP TABLE RECEIPTOLD;
DROP TABLE STOREOLD;

DROP VIEW LOGVIEW;
DROP VIEW PAYMENTVIEW;
DROP VIEW RECEIPTITEMVIEW;
DROP VIEW RECEIPTVIEW;
DROP VIEW STOREVIEW;